# -*- coding: utf-8 -*-
"""Agriculture_crop_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyOJrf5u73nIwpAQWWXH9PVkoReXypXd
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("datafile (1).csv")

df.head()

df.info()

df.isnull().sum

df.describe()

from sklearn.preprocessing import LabelEncoder

le_crop = LabelEncoder()
le_state = LabelEncoder()

df["Crop"] = le_crop.fit_transform(df["Crop"])
df["State"] = le_state.fit_transform(df["State"])

df.head()

print(df.columns)

from sklearn.preprocessing import LabelEncoder

le_crop = LabelEncoder()
le_state = LabelEncoder()

X.loc[:, "Crop"] = le_crop.fit_transform(X["Crop"])
X.loc[:, "State"] = le_state.fit_transform(X["State"])

print(df.columns.tolist())

df.columns = df.columns.str.strip()
print(df.columns.tolist())

X = df[[
    "Crop",
    "State",
    "Cost of Cultivation (`/Hectare) A2+FL",
    "Cost of Cultivation (`/Hectare) C2"
]]

y = df["Yield (Quintal/ Hectare)"]

X = df[[
    "Crop",
    "State",
    "Cost of Cultivation (`/Hectare) A2+FL",
    "Cost of Cultivation (`/Hectare) C2"
]]

y = df["Yield (Quintal/ Hectare)"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Train Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

print("Model Trained Successfully")

y_pred = model.predict(X_test)

print(y_pred)

from sklearn.metrics import r2_score, mean_absolute_error

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Yield")
plt.ylabel("Predicted Yield")
plt.title("Actual vs Predicted Yield")
plt.show()

result = pd.DataFrame({
    "Actual Yield": y_test.values,
    "Predicted Yield": y_pred
})

result.head(10)

from sklearn.metrics import r2_score, mean_absolute_error

print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))